#!/bin/bash
# 宝塔面板VNC操作指南

echo "=== VNC图形桌面操作宝塔面板 ==="
echo ""
echo "📍 当前Firefox窗口数: $(ps aux | grep firefox | grep -v grep | wc -l)"
echo ""
echo "🖥️ VNC访问方式:"
echo "1. 下载VNC Viewer: https://www.realvnc.com/download/viewer/"
echo "2. 连接: 150.109.204.23:5901"
echo "3. 密码: 见 PASSWORDS.md"
echo ""
echo "🌐 宝塔面板地址尝试:"
echo "- http://localhost:8888"
echo "- http://10.7.0.5:8888"
echo "- http://82.157.20.7:8888 (TOOLS.md中的地址)"
echo ""
echo "⚠️  如果上述地址都无法访问，可能需要:"
echo "1. 检查宝塔面板是否安装"
echo "2. 检查宝塔面板服务状态"
echo "3. 或重新安装宝塔面板"
echo ""
echo "✅ 替代方案:"
echo "当前系统已通过Nginx部署在 http://localhost:8081"
echo "可以配置SSL后使用（摄像头可用）"
