#!/bin/bash
# 宝塔面板自动化部署NCM转换器

echo "============================================================"
echo "🚀 NCM转换器 - 宝塔面板部署"
echo "============================================================"
echo ""

# 检查应用是否运行
if ! lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "❌ Web应用未运行"
    echo "🔄 启动应用..."
    bash /home/ubuntu/.openclaw/workspace/scripts/start_ncm_web.sh
fi

echo "✅ Web应用运行中"
echo ""

# 显示部署信息
echo "============================================================"
echo "📋 部署信息"
echo "============================================================"
echo ""
echo "🌐 Web应用:"
echo "   本地地址: http://localhost:5001"
echo "   公网地址: http://服务器IP:5001"
echo ""
echo "🔧 宝塔面板:"
echo "   地址: http://82.157.20.7:8888/fs123456"
echo ""
echo "🌐 域名配置:"
echo "   域名: ncm.dhmip.cn"
echo "   反向代理: http://127.0.0.1:5001"
echo "   SSL: Let's Encrypt"
echo ""
echo "🧪 测试域名:"
echo "   域名: ceshi.dhmip.cn"
echo "   反向代理: http://127.0.0.1:5000"
echo ""
echo "============================================================"
echo "📝 手动部署步骤"
echo "============================================================"
echo ""
echo "1. 登录宝塔面板"
echo "   地址: http://82.157.20.7:8888/fs123456"
echo ""
echo "2. 创建网站"
echo "   域名: ncm.dhmip.cn"
echo "   根目录: /www/wwwroot/ncm.dhmip.cn"
echo "   PHP版本: 纯静态"
echo ""
echo "3. 配置反向代理"
echo "   代理名称: NCM转换器"
echo "   目标URL: http://127.0.0.1:5000"
echo ""
echo "4. 申请SSL证书"
echo "   SSL → Let's Encrypt → 申请"
echo ""
echo "5. 测试访问"
echo "   https://ncm.dhmip.cn"
echo ""
echo "============================================================"
echo "💡 提示"
echo "============================================================"
echo ""
echo "✅ Web应用已运行在端口5000"
echo "✅ 测试脚本已通过所有测试"
echo "✅ 部署文档已准备完成"
echo ""
echo "⏭️  下一步:"
echo "   在VNC中打开宝塔面板"
echo "   按照上述步骤手动配置"
echo "   或者在浏览器中访问配置"
echo ""
echo "🔧 VNC访问:"
echo "   http://服务器IP:6080/vnc.html"
echo ""
